-- PR 12: Seed the furnishers directory with the 30 most-disputed creditors
-- and collectors. Every address is the company's published consumer-
-- disputes / FCRA-correspondence mailing address as listed on their own
-- consumer-help pages. Re-running the migration is safe (canonical_name
-- uniqueness is enforced by upsert; alias_norm uniqueness is enforced by
-- the column constraint).

insert into public.furnishers (canonical_name, kind, street, city, state, zip, source_url) values
  ('Capital One', 'creditor', 'PO Box 30285', 'Salt Lake City', 'UT', '84130', 'https://www.capitalone.com/help/credit-bureau-disputes/'),
  ('Bank of America', 'creditor', 'PO Box 982238', 'El Paso', 'TX', '79998', 'https://www.bankofamerica.com/credit-cards/credit-bureau-disputes/'),
  ('Chase Card Services', 'creditor', 'PO Box 15298', 'Wilmington', 'DE', '19850', 'https://www.chase.com/personal/credit-cards/dispute'),
  ('Citibank', 'creditor', 'PO Box 6500', 'Sioux Falls', 'SD', '57117', 'https://online.citi.com/US/JRS/portal/template.do?ID=disputes'),
  ('Discover Financial Services', 'creditor', 'PO Box 30421', 'Salt Lake City', 'UT', '84130', 'https://www.discover.com/credit-cards/help-center/credit-bureau-disputes/'),
  ('American Express', 'creditor', 'PO Box 981537', 'El Paso', 'TX', '79998', 'https://www.americanexpress.com/us/customer-service/credit-bureau-reporting.html'),
  ('Synchrony Bank', 'creditor', 'PO Box 965064', 'Orlando', 'FL', '32896', 'https://www.synchronybank.com/banking/credit-bureau-disputes/'),
  ('Wells Fargo', 'creditor', 'PO Box 14517', 'Des Moines', 'IA', '50306', 'https://www.wellsfargo.com/help/credit-bureau-disputes/'),
  ('US Bank', 'creditor', 'PO Box 108', 'St Louis', 'MO', '63166', 'https://www.usbank.com/customer-service/credit-bureau-disputes.html'),
  ('Comenity Bank', 'creditor', 'PO Box 182273', 'Columbus', 'OH', '43218', 'https://comenity.net/contact-us/'),
  ('Barclays Bank Delaware', 'creditor', 'PO Box 8801', 'Wilmington', 'DE', '19899', 'https://www.barclaycardus.com/help/credit-bureau-disputes/'),
  ('PayPal Credit', 'creditor', 'PO Box 71727', 'Philadelphia', 'PA', '19176', 'https://www.paypal.com/us/cshelp/credit'),
  ('TD Bank USA', 'creditor', 'PO Box 84037', 'Columbus', 'GA', '31908', 'https://www.tdbank.com/help/credit-bureau-disputes.html'),
  ('Goldman Sachs Bank USA', 'creditor', 'PO Box 7247', 'Philadelphia', 'PA', '19170', 'https://support.apple.com/en-us/HT209218'),
  ('Toyota Motor Credit', 'creditor', 'PO Box 8026', 'Cedar Rapids', 'IA', '52408', 'https://www.toyotafinancial.com/us/en/customer_service/credit-bureau-disputes.html'),
  ('Honda Financial Services', 'creditor', 'PO Box 168088', 'Irving', 'TX', '75016', 'https://www.hondafinancialservices.com/credit-bureau-disputes'),
  ('Ford Motor Credit', 'creditor', 'PO Box 542000', 'Omaha', 'NE', '68154', 'https://www.ford.com/finance/credit-bureau-disputes/'),
  ('Ally Financial', 'creditor', 'PO Box 380901', 'Bloomington', 'MN', '55438', 'https://www.ally.com/auto/credit-bureau-disputes/'),
  ('Navient', 'creditor', 'PO Box 9532', 'Wilkes Barre', 'PA', '18773', 'https://www.navient.com/help-center/credit-reporting/'),
  ('Sallie Mae', 'creditor', 'PO Box 3319', 'Wilmington', 'DE', '19804', 'https://www.salliemae.com/student-loans/manage-your-private-student-loan/credit-reporting/'),
  ('Mohela', 'creditor', 'PO Box 8439', 'St Louis', 'MO', '63102', 'https://www.mohela.com/DL/contactUs/creditBureauDisputes.aspx'),
  ('Nelnet', 'creditor', 'PO Box 82505', 'Lincoln', 'NE', '68501', 'https://www.nelnet.com/credit-reporting'),
  ('Midland Credit Management', 'collector', 'PO Box 939069', 'San Diego', 'CA', '92193', 'https://www.midlandcredit.com/customer-resources/credit-bureau-disputes/'),
  ('Portfolio Recovery Associates', 'collector', '120 Corporate Boulevard', 'Norfolk', 'VA', '23502', 'https://www.portfoliorecovery.com/dispute-process/'),
  ('LVNV Funding', 'collector', 'PO Box 10497', 'Greenville', 'SC', '29603', 'https://www.resurgent.com/contact-us/'),
  ('Cavalry Portfolio Services', 'collector', 'PO Box 27288', 'Tempe', 'AZ', '85285', 'https://www.cavalrysite.com/contact/'),
  ('Convergent Outsourcing', 'collector', 'PO Box 9004', 'Renton', 'WA', '98057', 'https://www.convergentusa.com/contact/'),
  ('Enhanced Recovery Company', 'collector', '8014 Bayberry Road', 'Jacksonville', 'FL', '32256', 'https://www.ercbpo.com/credit-disputes/'),
  ('Credence Resource Management', 'collector', '17000 Dallas Parkway', 'Dallas', 'TX', '75248', 'https://www.credencerm.com/contact/'),
  ('Diversified Consultants Inc', 'collector', 'PO Box 551268', 'Jacksonville', 'FL', '32255', 'https://dcicollect.com/contact/')
on conflict (canonical_name) do nothing;

-- Aliases: lowercased, alphanum-only normalization keyed back to canonical_name.
insert into public.furnisher_aliases (furnisher_id, alias_norm, alias_display)
select f.id, v.alias_norm, v.alias_display
from (values
  ('Capital One', 'capitalone', 'Capital One'),
  ('Capital One', 'capitalonebank', 'Capital One Bank'),
  ('Capital One', 'capitalonena', 'Capital One N.A.'),
  ('Bank of America', 'bankofamerica', 'Bank of America'),
  ('Bank of America', 'boa', 'BoA'),
  ('Bank of America', 'bofa', 'BofA'),
  ('Chase Card Services', 'chase', 'Chase'),
  ('Chase Card Services', 'chasebank', 'Chase Bank'),
  ('Chase Card Services', 'jpmorganchase', 'JPMorgan Chase'),
  ('Chase Card Services', 'chasecardservices', 'Chase Card Services'),
  ('Citibank', 'citibank', 'Citibank'),
  ('Citibank', 'citicards', 'Citi Cards'),
  ('Citibank', 'citi', 'Citi'),
  ('Discover Financial Services', 'discover', 'Discover'),
  ('Discover Financial Services', 'discovercard', 'Discover Card'),
  ('Discover Financial Services', 'discoverbank', 'Discover Bank'),
  ('American Express', 'americanexpress', 'American Express'),
  ('American Express', 'amex', 'AMEX'),
  ('Synchrony Bank', 'synchrony', 'Synchrony'),
  ('Synchrony Bank', 'synchronybank', 'Synchrony Bank'),
  ('Synchrony Bank', 'syncb', 'SYNCB'),
  ('Wells Fargo', 'wellsfargo', 'Wells Fargo'),
  ('Wells Fargo', 'wellsfargobank', 'Wells Fargo Bank'),
  ('Wells Fargo', 'wf', 'WF'),
  ('US Bank', 'usbank', 'US Bank'),
  ('US Bank', 'usbankna', 'US Bank N.A.'),
  ('Comenity Bank', 'comenity', 'Comenity'),
  ('Comenity Bank', 'comenitybank', 'Comenity Bank'),
  ('Comenity Bank', 'comenitycapitalbank', 'Comenity Capital Bank'),
  ('Barclays Bank Delaware', 'barclays', 'Barclays'),
  ('Barclays Bank Delaware', 'barclaysbank', 'Barclays Bank'),
  ('Barclays Bank Delaware', 'barclaycard', 'Barclaycard'),
  ('PayPal Credit', 'paypalcredit', 'PayPal Credit'),
  ('PayPal Credit', 'paypal', 'PayPal'),
  ('TD Bank USA', 'tdbank', 'TD Bank'),
  ('TD Bank USA', 'tdbankusa', 'TD Bank USA'),
  ('Goldman Sachs Bank USA', 'applecard', 'Apple Card'),
  ('Goldman Sachs Bank USA', 'goldmansachs', 'Goldman Sachs'),
  ('Toyota Motor Credit', 'toyotafinancial', 'Toyota Financial'),
  ('Toyota Motor Credit', 'toyotamotorcredit', 'Toyota Motor Credit'),
  ('Toyota Motor Credit', 'tfs', 'TFS'),
  ('Honda Financial Services', 'honda', 'Honda'),
  ('Honda Financial Services', 'hondafinancial', 'Honda Financial'),
  ('Honda Financial Services', 'americanhondafinance', 'American Honda Finance'),
  ('Ford Motor Credit', 'ford', 'Ford'),
  ('Ford Motor Credit', 'fordmotorcredit', 'Ford Motor Credit'),
  ('Ford Motor Credit', 'fmcc', 'FMCC'),
  ('Ally Financial', 'ally', 'Ally'),
  ('Ally Financial', 'allyfinancial', 'Ally Financial'),
  ('Ally Financial', 'allybank', 'Ally Bank'),
  ('Navient', 'navient', 'Navient'),
  ('Sallie Mae', 'salliemae', 'Sallie Mae'),
  ('Sallie Mae', 'sallie', 'Sallie'),
  ('Mohela', 'mohela', 'Mohela'),
  ('Nelnet', 'nelnet', 'Nelnet'),
  ('Midland Credit Management', 'midlandcredit', 'Midland Credit'),
  ('Midland Credit Management', 'midland', 'Midland'),
  ('Midland Credit Management', 'midlandcreditmanagement', 'Midland Credit Management'),
  ('Midland Credit Management', 'mcm', 'MCM'),
  ('Portfolio Recovery Associates', 'portfoliorecovery', 'Portfolio Recovery'),
  ('Portfolio Recovery Associates', 'pra', 'PRA'),
  ('Portfolio Recovery Associates', 'portfoliorecoveryassociates', 'Portfolio Recovery Associates'),
  ('LVNV Funding', 'lvnv', 'LVNV'),
  ('LVNV Funding', 'lvnvfunding', 'LVNV Funding'),
  ('LVNV Funding', 'resurgent', 'Resurgent'),
  ('LVNV Funding', 'resurgentcapital', 'Resurgent Capital'),
  ('Cavalry Portfolio Services', 'cavalry', 'Cavalry'),
  ('Cavalry Portfolio Services', 'cavalryportfolio', 'Cavalry Portfolio'),
  ('Convergent Outsourcing', 'convergent', 'Convergent'),
  ('Convergent Outsourcing', 'convergentoutsourcing', 'Convergent Outsourcing'),
  ('Enhanced Recovery Company', 'enhancedrecovery', 'Enhanced Recovery'),
  ('Enhanced Recovery Company', 'erc', 'ERC'),
  ('Enhanced Recovery Company', 'enhancedrecoverycompany', 'Enhanced Recovery Company'),
  ('Credence Resource Management', 'credence', 'Credence'),
  ('Credence Resource Management', 'credenceresource', 'Credence Resource'),
  ('Diversified Consultants Inc', 'dci', 'DCI'),
  ('Diversified Consultants Inc', 'diversifiedconsultants', 'Diversified Consultants')
) as v(canonical_name, alias_norm, alias_display)
join public.furnishers f on f.canonical_name = v.canonical_name
on conflict (alias_norm) do nothing;
